"""empty message

Revision ID: 8e12932de353
Revises: 0aec0390855b
Create Date: 2016-11-27 21:31:11.571957

"""

# revision identifiers, used by Alembic.
revision = '8e12932de353'
down_revision = '0aec0390855b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horario')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('hora_inicio', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('hora_fim', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='horario_pkey')
    )
    ### end Alembic commands ###
